---
pipeline:
    name: erfs
    description: "prepare MiDAS-seq data for analysis in the interactive app"
    # version: v0.0.1
# suiteVersions:
#     suiteName: v0.0.0
actions: 
    _global:   
        environment: erfs-mdi-tools
        condaFamilies:
            - base
            - genomics
            - r-4.4
    collate:
        order: 1
        optionFamilies:
            - genome
            - bin
            - bam-files
            - mapq
            - calls
        resources:
            required:
                total-ram: 8G
            recommended: 
                n-cpu: 4
                ram-per-cpu: 2G
        job-manager:
            recommended:
                time-limit: 2:00:00
        description: "collate read data across all samples into high resolution bins with scores"
package:
    collate: # the pipeline action after which a data package should assembled
        uploadType: erfd-midas-seq # a signal to the Stage 2 framework regarding the package contents
        files:
            binCounts:
                type: rds
                file: $DATA_GENOME_PREFIX.binCounts.rds
            externalCalls:
                type: rds
                file: $DATA_GENOME_PREFIX.calls.rds
            # scores:
            #     type: rds
            #     file: $DATA_FILE_PREFIX.scores.rds
