#----------------------------------------------------------------------
# R package dependencies common to many apps
#----------------------------------------------------------------------
packages:
  R:  
    - imager
  Bioconductor: null
