---
pipeline:
    name: genome
    description: "prepare genome files for binned analysis"
    # version: v0.0.1
# suiteVersions:
#     suiteName: v0.0.0
actions: 
    _global:   
        environment: erfs-mdi-tools
        condaFamilies:
            - base
            - genomics
            - r-4.4
    bin:
        order: 1
        optionFamilies:
            - genome
            - bin
        resources:
            required:
                total-ram: 8G
            recommended: 
                n-cpu: 4
                ram-per-cpu: 2G
        job-manager:
            recommended:
                time-limit: 1:00:00
        description: "create genome-level bin files on nuclear chroms with exclusion flag and percent GC"
